name: adeo_testapp
description: A Flutter App to enhance education
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.4

dependencies:
  auto_route: ^4.2.1
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_html: ^2.2.1
  flutter_localizations:
    sdk: flutter
  flutter_switch: ^0.3.2
  google_fonts: ^3.0.1
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
  auto_route_generator:
  build_runner:

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

  fonts:
    - family: Hamelin
      fonts:
        - asset: fonts/Hamelin.ttf
